apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: orion
  name: orion
spec:
  ports:
  - port: 1026
    protocol: TCP
    targetPort: 1026
  selector:
    run: orion
status:
  loadBalancer: {}
