apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mongo
    spec:
      containers:
      - image: mongo:3.6
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
status: {}
