# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.hostname = "oshift.local"
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.network "forwarded_port", guest: 8443, host: 8443
  config.vm.network "forwarded_port", guest: 4041, host: 4041
  config.vm.network "forwarded_port", guest: 1883, host: 1883
  config.vm.network "forwarded_port", guest: 1884, host: 1884
  config.vm.network "forwarded_port", guest: 1026, host: 1026
  config.vm.network "forwarded_port", guest: 5001, host: 5001

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "oshift.local"
    vb.memory = "5120"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end

   $enable_serial_logging = false
end
